name: release-minor-trigger

on:
  pull_request:
    branches: 
      - master
    types: [ closed ]

jobs:
  release-minor-trigger:
    if: contains(github.event.pull_request.labels.*.name, 'minor-release') && !contains(github.event.pull_request.labels.*.name, 'patch-release')
    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET 9.0.x SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
